Develop
reliqarts/laravel-guided-image pull request #21
Opened 2019-10-27 03:04 UTC by jpedryc

#20 
Added initial `ReliqArts\GuidedImage\Demand\Image` & `ReliqArts\GuidedImage\Demand\ExistingImage` unit tests

2019-10-28 07:22 UTC, reliq requested changes
Thanks for this.

2019-10-28 07:22 UTC, reliq commented on tests/Unit/Demand/ImageTest.php
> +    public function testGetWidth($width, ?int $expectedResult)
Please add return types; e.g. `: null`

2019-10-29 20:48 UTC, jpedryc commented on tests/Unit/Demand/ImageTest.php
> +    public function testGetWidth($width, ?int $expectedResult)
Added 👍

2019-10-29 21:06 UTC, reliq approved these changes
Thank you.

2019-10-29 21:06 UTC, reliq commented on composer.json
> +    "test-demands": "vendor/bin/phpunit --testdox tests/Unit/Demand"
I don't think we'll need this going forward so I might remove it soon.

2019-10-29 21:09 UTC, merged

2019-10-29 21:19 UTC, jpedryc commented
Sry for taking your time, it's my first ever push targeting not my repo - have a question 😄 Could you give me a hint about "not fully covered"? I thought the requirement is to have "touched" every function of a given class (with the annotation of `@cover`). Is the strategy of unit testing to cover also the methods of the parent classes?

2019-10-29 21:25 UTC, reliq commented
No worries @jpedryc, you are correct. 

It was my mistake, I actually forgot I had already covered `.../Demand/Dummy.php`, `.../Demand/Resize.php` and `../Demand/Thumbnail.php`

I have gone ahead and merged this in. 

Thank you again.

Cheers! 🍻

2019-10-29 21:46 UTC, jpedryc commented
Awesome 👍 Like the package, was looking for something like that couple months ago. Will try to help more here.

2019-10-30 18:53 UTC, reliq commented
@jpedryc thank you!